### ISSUE TITLE
int type error when training models

### ISSUE THREAD

**Issue by xiaoyang-sde** [gundamMC/animius#3]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 0-th value returned by pyfunc_1 is int64, but expects int32
	 [[{{node PyFunc}}]]
	 [[{{node IteratorGetNext}}]]
	 [[{{node RemoteCall}}]]
	 [[{{node chatbot/IteratorGetNext_1}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/xasiimov/Documents/Develop/Python/animius/animius/Console.py", line 2165, in run
    self.console.handle_command(task)
  File "/Users/xasiimov/Documents/Develop/Python/animius/animius/Console.py", line 2112, in handle_command
    result = self.commands[command][0].__call__(**kwargs)
  File "/Users/xasiimov/Documents/Develop/Python/animius/animius/Console.py", line 1194, in predict
    result = self.models[kwargs['name']].item.predict(kwargs['input'], save_path=kwargs['save_path'])
  File "/Users/xasiimov/Documents/Develop/Python/animius/animius/Chatbot/ChatbotModel.py", line 402, in predict
    outputs.append(self.sess.run(self.infer))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 0-th value returned by pyfunc_1 is int64, but expects int32
	 [[{{node PyFunc}}]]
	 [[{{node IteratorGetNext}}]]
	 [[{{node RemoteCall}}]]
	 [[node chatbot/IteratorGetNext_1 (defined at /Users/xasiimov/Documents/Develop/Python/animius/animius/Chatbot/ChatbotModel.py:281) ]]

```

**Comment by xiaoyang-sde** [comment]
Commit dddacf8 has successfully fixed this bug.
